version: '2'
services:

  deploymentservice:
    image: wilhelmstephan/grpc-api-for-saltstack-deployment-service
    ports:
      - "40011:40011"
    command: ["java", "-jar", "/fapra/gRPCContainer.jar", "40011"]
    
  deploymentscript:
    build: ./DockerContainerWordpressDeploymentScript/
    links:
      - "deploymentservice:ssds1"
    environment:
      - IP_SERVER=ssds1
      - PORT_SERVER=40011
      # PROVIDE YOUR INFORMATION:
      - KEY_PAIR_NAME=CHANGE
      - KEY_ID=CHANGE
      - KEY_SECRET=CHANGE
      - SECURITY_GROUP_NAME=CHANGE
    depends_on:
      - deploymentservice
    command: ["/fapra/scenario1.sh"]
